# Site specific settings
title: "cha-duh"
name: "joshuaowens.info"
keywords: "joshua, owens, cha-duh, cha, duh"
baseurl: "/"
url: "http://www.joshuaowens.info"
description: "front-page-of-my-life"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
# disqus: test
# twitter: 
# facebook: 
github: cha-duh
google: joshua.w.owens

# Build settings
markdown: kramdown
permalink: /:categories/:title/
