# Site specific settings
title: "cha-duh"
name: "cha-duh"
keywords: "joshua, owens, cha-duh, cha, duh"
baseurl: ""
url: "https://cha-duh.github.io"
description: "front-page-of-my-life"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
# lang_alternate: ""
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: cha-duh-github-io 
# twitter: 
# facebook: 
github: cha-duh
google: joshua.w.owens

# Build settings
markdown: kramdown
permalink: /:categories/:title/
